version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - $PWD:/usr/src/app # ローカルをコンテナ内にマウント
    command: sh -c "yarn start"
    ports:
      - "60338:3000"
    stdin_open: true
